import { z } from 'zod';

const schema = z.object({
  DATABASE_URL: z.string().url(),
  AUTH_SECRET: z.string().min(16),
  AUTH_URL: z.string().url(),
  GOOGLE_CLIENT_ID: z.string().optional(),
  GOOGLE_CLIENT_SECRET: z.string().optional(),
  WORKER_URL: z.string().url().default('http://localhost:8001'),
  WORKER_HMAC_SECRET: z.string().min(8),
  ANTHROPIC_API_KEY: z.string().optional(),
  KMS_KEY: z.string().regex(/^[a-f0-9]{64}$/i).optional(),
  PLAID_CLIENT_ID: z.string().optional(),
  PLAID_SECRET: z.string().optional(),
  PLAID_ENV: z.enum(['sandbox', 'development', 'production']).default('sandbox'),
  EMAIL_DOMAIN: z.string().default('in.perfin.app'),
  EMAIL_HASH_SECRET: z.string().min(8).default('dev-email-hash-secret'),
  PLAID_WEBHOOK_URL: z.string().url().default('http://localhost:8001/webhooks/plaid'),
  STRIPE_SECRET_KEY: z.string().optional(),
  STRIPE_PRICE_PLUS: z.string().optional(),
  STRIPE_PRICE_PRO:  z.string().optional(),
  NEXT_PUBLIC_APP_URL: z.string().url().default('http://localhost:3000'),
  NEXT_PUBLIC_VAPID_PUBLIC_KEY: z.string().optional(),
});

export const env = schema.parse({
  DATABASE_URL: process.env.DATABASE_URL,
  AUTH_SECRET: process.env.AUTH_SECRET,
  AUTH_URL: process.env.AUTH_URL,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  WORKER_URL: process.env.WORKER_URL,
  WORKER_HMAC_SECRET: process.env.WORKER_HMAC_SECRET,
  ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
  KMS_KEY: process.env.KMS_KEY,
  PLAID_CLIENT_ID: process.env.PLAID_CLIENT_ID,
  PLAID_SECRET: process.env.PLAID_SECRET,
  PLAID_ENV: process.env.PLAID_ENV,
  EMAIL_DOMAIN: process.env.EMAIL_DOMAIN,
  EMAIL_HASH_SECRET: process.env.EMAIL_HASH_SECRET,
  PLAID_WEBHOOK_URL: process.env.PLAID_WEBHOOK_URL,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_PRICE_PLUS: process.env.STRIPE_PRICE_PLUS,
  STRIPE_PRICE_PRO: process.env.STRIPE_PRICE_PRO,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_VAPID_PUBLIC_KEY: process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY,
});
