export * from './money';
export * from './text';
export * from './categories';
export * from './normalize';
export * from './categorize/types';
export * from './categorize/rules';
export * from './categorize/seed-rules';
export { createClaudeCategorizer, type ClaudeCategorizer, type ClaudeOptions } from './categorize/claude';
export * from './categorize/orchestrate';
export * from './recurring/types';
export * from './recurring/detect';
export * from './recurring/cadence';
export * from './anomalies/types';
export * from './anomalies/detect';
export * from './insights/types';
export * from './insights/drift';
export { generateNarrative, type NarrativeInput, type NarrativeOptions, type Narrative, type StatBlock } from './insights/narrative';
export * from './insights/generate';
export * from './budget/status';
export * from './home/kpi';
