import type { Rule } from './types';

export const SEED_RULES: Rule[] = [
  // priority 10 — Income / Investment
  { priority: 10, matchType: 'contains', pattern: 'salary',          category: 'Income' },
  { priority: 10, matchType: 'contains', pattern: 'payroll',         category: 'Income' },
  { priority: 10, matchType: 'contains', pattern: 'direct deposit',  category: 'Income' },
  { priority: 10, matchType: 'contains', pattern: 'paycheck',        category: 'Income' },
  { priority: 10, matchType: 'contains', pattern: 'refund',          category: 'Income' },
  { priority: 10, matchType: 'contains', pattern: 'reimbursement',   category: 'Income' },
  { priority: 10, matchType: 'contains', pattern: 'cashback',        category: 'Income' },
  { priority: 10, matchType: 'contains', pattern: 'interest',        category: 'Investment' },
  { priority: 10, matchType: 'contains', pattern: 'dividend',        category: 'Investment' },
  { priority: 10, matchType: 'contains', pattern: 'capital gain',    category: 'Investment' },

  // priority 9 — high-confidence merchants
  { priority: 9, matchType: 'contains', pattern: 'swiggy',         category: 'Food' },
  { priority: 9, matchType: 'contains', pattern: 'zomato',         category: 'Food' },
  { priority: 9, matchType: 'contains', pattern: 'ubereats',       category: 'Food' },
  { priority: 9, matchType: 'contains', pattern: 'doordash',       category: 'Food' },
  { priority: 9, matchType: 'contains', pattern: 'grubhub',        category: 'Food' },
  { priority: 9, matchType: 'contains', pattern: 'restaurant',     category: 'Food' },
  { priority: 9, matchType: 'contains', pattern: 'cafe',           category: 'Food' },
  { priority: 9, matchType: 'contains', pattern: 'coffee',         category: 'Food' },
  { priority: 9, matchType: 'contains', pattern: 'starbucks',      category: 'Food' },
  { priority: 9, matchType: 'contains', pattern: 'mcdonald',       category: 'Food' },
  { priority: 9, matchType: 'contains', pattern: 'pizza',          category: 'Food' },
  { priority: 9, matchType: 'contains', pattern: 'walmart',        category: 'Groceries' },
  { priority: 9, matchType: 'contains', pattern: 'target',         category: 'Groceries' },
  { priority: 9, matchType: 'contains', pattern: 'costco',         category: 'Groceries' },
  { priority: 9, matchType: 'contains', pattern: 'whole foods',    category: 'Groceries' },
  { priority: 9, matchType: 'contains', pattern: 'trader joe',     category: 'Groceries' },
  { priority: 9, matchType: 'contains', pattern: 'blinkit',        category: 'Groceries' },
  { priority: 9, matchType: 'contains', pattern: 'uber',           category: 'Transport' },
  { priority: 9, matchType: 'contains', pattern: 'lyft',           category: 'Transport' },
  { priority: 9, matchType: 'contains', pattern: 'ola',            category: 'Transport' },
  { priority: 9, matchType: 'contains', pattern: 'rapido',         category: 'Transport' },
  { priority: 9, matchType: 'contains', pattern: 'netflix',        category: 'Subscription' },
  { priority: 9, matchType: 'contains', pattern: 'spotify',        category: 'Subscription' },
  { priority: 9, matchType: 'contains', pattern: 'youtube premium',category: 'Subscription' },
  { priority: 9, matchType: 'contains', pattern: 'icloud',         category: 'Subscription' },
  { priority: 9, matchType: 'contains', pattern: 'amazon prime',   category: 'Subscription' },
  { priority: 9, matchType: 'contains', pattern: 'disney',         category: 'Subscription' },

  // priority 8 — generic
  { priority: 8, matchType: 'contains', pattern: 'grocery',        category: 'Groceries' },
  { priority: 8, matchType: 'contains', pattern: 'supermarket',    category: 'Groceries' },
  { priority: 8, matchType: 'contains', pattern: 'gas station',    category: 'Transport' },
  { priority: 8, matchType: 'contains', pattern: 'shell',          category: 'Transport' },
  { priority: 8, matchType: 'contains', pattern: 'metro',          category: 'Transport' },
  { priority: 8, matchType: 'contains', pattern: 'electricity',    category: 'Utilities' },
  { priority: 8, matchType: 'contains', pattern: 'water bill',     category: 'Utilities' },
  { priority: 8, matchType: 'contains', pattern: 'internet',       category: 'Utilities' },
  { priority: 8, matchType: 'contains', pattern: 'mobile recharge',category: 'Utilities' },
  { priority: 8, matchType: 'contains', pattern: 'jio',            category: 'Utilities' },
  { priority: 8, matchType: 'contains', pattern: 'airtel',         category: 'Utilities' },
  { priority: 8, matchType: 'contains', pattern: 'pharmacy',       category: 'Medical' },
  { priority: 8, matchType: 'contains', pattern: 'hospital',       category: 'Medical' },
  { priority: 8, matchType: 'contains', pattern: 'doctor',         category: 'Medical' },
  { priority: 8, matchType: 'contains', pattern: 'apollo',         category: 'Medical' },
  { priority: 8, matchType: 'contains', pattern: 'flight',         category: 'Travel' },
  { priority: 8, matchType: 'contains', pattern: 'airline',        category: 'Travel' },
  { priority: 8, matchType: 'contains', pattern: 'hotel',          category: 'Travel' },
  { priority: 8, matchType: 'contains', pattern: 'airbnb',         category: 'Travel' },
  { priority: 8, matchType: 'contains', pattern: 'makemytrip',     category: 'Travel' },
  { priority: 8, matchType: 'contains', pattern: 'amazon',         category: 'Shopping' },
  { priority: 8, matchType: 'contains', pattern: 'flipkart',       category: 'Shopping' },
  { priority: 8, matchType: 'contains', pattern: 'myntra',         category: 'Shopping' },
  { priority: 8, matchType: 'contains', pattern: 'rent',           category: 'Rent' },
  { priority: 8, matchType: 'contains', pattern: 'lic',            category: 'Insurance' },
  { priority: 8, matchType: 'contains', pattern: 'insurance',      category: 'Insurance' },

  // priority 5 — fallbacks
  { priority: 5, matchType: 'contains', pattern: 'transfer',       category: 'Transfer' },
  { priority: 5, matchType: 'contains', pattern: 'imps',           category: 'Transfer' },
  { priority: 5, matchType: 'contains', pattern: 'neft',           category: 'Transfer' },
  { priority: 5, matchType: 'contains', pattern: 'upi',            category: 'Transfer' },
];
